name: Pull request

on: pull_request

jobs:
  generate_doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0
    - name: Generate Actions Documentation
      uses: f0rmiga/doc-generator-actions/github-actions@master
