name: Pull request

on: pull_request

jobs:
  generate_doc:
    runs-on: ubuntu-latest
    # TODO(f0rmiga): fix the doc-generator-actions first, then remove this.
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0
    - name: Generate Actions Documentation
      uses: SUSE/doc-generator-actions/github-actions@master
